package seas.angel.macdonald.chess2d.vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * Clase de la ventana (dialog) de Acerca De.
 *
 * @author Ángel Mac Donald
 */
public class Acerca extends javax.swing.JDialog {

    /**
     * Constructor por defecto (JDialog)
     * 
     * @param parent Frame de la ventana padre (pantalla)
     * @param modal boolean 
     */
    public Acerca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon imgAcercaDe = new ImageIcon("src/seas/angel/macdonald/chess2d/recursos/splash_screen.png");
        Icon icono = new ImageIcon (imgAcercaDe.getImage().getScaledInstance(jlSplashScreen.getWidth(), jlSplashScreen.getHeight(), Image.SCALE_DEFAULT));
        jlSplashScreen.setIcon(icono);
        setLocationRelativeTo(null);	
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSplashScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSplashScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSplashScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlSplashScreen;
    // End of variables declaration//GEN-END:variables
}
