package seas.angel.macdonald.chess2d.vista;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import seas.angel.macdonald.chess2d.modelo.dao.Gestor;
import seas.angel.macdonald.chess2d.modelo.Partida;


/**
 * Clase con la ventana donde se desarrolla la partida.
 * 
 * @author Ángel Mac Donald Gainza
 */
public class Pantalla extends javax.swing.JFrame {
    
    /**
     * Partida que guardará todos los datos relativos al juego en sí
     */
    private Partida partida;
    /**
     * Gestor que se encargará de guardar y cargar la partida
     */
    private final Gestor gestor;
    /**
     * Constructor por defecto de la ventana
     */
    public Pantalla() {
        initComponents();
        partida = new Partida("Jugador 1","BLANCAS","Jugador 2", "NEGRAS");
        cargaTablero();
        gestor = new Gestor(this);
        
        
    }
    
    
    /**
     * Getter de la partida.
     *
     * @return Partida partida.
     */
    public Partida getPartida() {
        return partida;
    }
    
    /**
     * Setter de la partida.
     *
     * @param partida Partida.
     */
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    
    /**
     * Método que carga el tablero (JPanel) en el frame.
     */
    private void cargaTablero() {
        panelContenedor.removeAll();
        PanelTablero t = new PanelTablero(this);
        panelContenedor.add(t, BorderLayout.CENTER);
        panelContenedor.setSize(595,550);
        panelContenedor.setVisible(true);
        pack();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        mnuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuCargar = new javax.swing.JMenuItem();
        mnuNueva = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuReglamentoChess2D = new javax.swing.JMenuItem();
        mnuInterfazChess2D = new javax.swing.JMenuItem();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor);
        panelContenedor.setBounds(0, 0, 0, 0);

        mnuArchivo.setText("Archivo");

        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuGuardar);

        mnuCargar.setText("Cargar");
        mnuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCargar);

        mnuNueva.setText("Nueva");
        mnuNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuNueva);

        mnuBar.add(mnuArchivo);

        mnuAyuda.setText("Ayuda");

        mnuReglamentoChess2D.setText("Reglamento de Chess 2D");
        mnuReglamentoChess2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReglamentoChess2DActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuReglamentoChess2D);

        mnuInterfazChess2D.setText("Tutorial interfaz Chess 2D");
        mnuInterfazChess2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInterfazChess2DActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuInterfazChess2D);

        mnuAcercaDe.setText("Acerca de Chess 2D");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcercaDe);

        mnuBar.add(mnuAyuda);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se encarga de llamar al método guardar del gestor.
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        
        gestor.guardar();
        
    }//GEN-LAST:event_mnuGuardarActionPerformed
    /**
     * Método que se encarga básicamente de llamar al método cargar del gestor
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargarActionPerformed
        partida.getGameLogScreen().dispose();
        gestor.cargar();
        cargaTablero();
        this.setSize(600,600);
        this.setVisible(true);
    }//GEN-LAST:event_mnuCargarActionPerformed
    /**
     * Método que se encarga básicamente en crear una nueva partida
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaActionPerformed
        partida.getGameLogScreen().dispose();
        partida = new Partida("Jugador 1","BLANCAS","Jugador 2", "NEGRAS");
        cargaTablero();
        this.setSize(600,600);
        this.setVisible(true);
        
    }//GEN-LAST:event_mnuNuevaActionPerformed

    /**
     * Método qeu se encarga de visualizar el reglamento de Chess2D
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuReglamentoChess2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReglamentoChess2DActionPerformed
        // TODO add your handling code here:
        try {
            File path = new File ("src/seas/angel/macdonald/chess2d/recursos/reglamento_chess_2d.pdf");
            Desktop.getDesktop().open(path);
        }catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuReglamentoChess2DActionPerformed

    /**
     * Método que se encarga abrir la ventana AcercaDe
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        // TODO add your handling code here:
        Acerca acercaDe = new Acerca(this,true);
        
        acercaDe.setTitle("Chess 2D");
        
        //acercaDe.setLocationRelativeTo(null);
        //p.setSize(600,600);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_mnuAcercaDeActionPerformed

    /**
     * Método que se encarga abrir el tutorial de la interfaz de Chess 2D
     * 
     * @param evt java.awt.event.ActionEvent
     */
    private void mnuInterfazChess2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInterfazChess2DActionPerformed
        // TODO add your handling code here:
        try {
            File path = new File ("src/seas/angel/macdonald/chess2d/recursos/interfaz_chess_2d.pdf");
            Desktop.getDesktop().open(path);
        }catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuInterfazChess2DActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuCargar;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuInterfazChess2D;
    private javax.swing.JMenuItem mnuNueva;
    private javax.swing.JMenuItem mnuReglamentoChess2D;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
